DEFAULT_KEYWORDS = [
    "formazione",
    "sviluppo competenze",
    "competenze digitali",
    "digital",
    "skills",
    "training",
    "advanced digital skills",
    "govtech",
    "public administration",
    "public sector",
    "administration",
    "transizione digitale",
    "innovazione amministrativa",
    "assistenza digitale",
    "ict",
    "sistemi informativi",
    "governance digitale",
    "capacity building",
    "capitale umano",
    "rafforzamento amministrativo",
    "servizi e soluzioni tecnologiche",
    "performa pa",
    "linea 5",
    "pnrr",
    "performance",
    "risorse umane",
    "pa",
]

DEFAULT_SCOPES = [
    "pubblica amministrazione",
    "dipendenti pubblici",
    "enti locali",
    "pa centrali",
    "pa locali",
    "pa regionali",
    "ministeri",
    "regioni",
    "comuni",
    "scuola",
]

SOURCES = [
    {
        "id": "agid-rss",
        "name": "AgID RSS",
        "kind": "rss",
        "url": "https://www.agid.gov.it/it/rss.xml",
        "publisher": "AgID",
        "reliability": "official",
        "enabled": False,
    },
    {
        "id": "fasi-rss",
        "name": "FASI Feed",
        "kind": "rss",
        "url": "https://www.fasi.eu/it/feed.html",
        "publisher": "FASI",
        "reliability": "aggregator",
        "enabled": False,
    },
    {
        "id": "invitalia-rss",
        "name": "Invitalia RSS",
        "kind": "rss",
        "url": "https://www.invitalia.it/rss",
        "publisher": "Invitalia",
        "reliability": "official",
        "enabled": True,
    },
    {
        "id": "sicilia-servizi-informativi-bandi",
        "name": "Regione Sicilia - Servizi Informativi Bandi",
        "kind": "html",
        "url": "https://www.regione.sicilia.it/istituzioni/servizi-informativi/bandi",
        "publisher": "Regione Siciliana",
        "reliability": "official",
        "enabled": True,
        "list_selector": "article, .views-row, .card, .item-list li, .node",
        "title_selector": "h2, h3, .field-content a, .card-title, .node-title",
        "link_selector": "a",
        "summary_selector": "p, .field-content, .card-text, .content",
        "date_selector": "time, .date, .submitted, .meta",
    },
    {
        "id": "google-news-digital-pa",
        "name": "Google News - Bandi Formazione Digitale PA",
        "kind": "rss",
        "url": "https://news.google.com/rss/search?q=bando+formazione+digitale+PA+OR+PNRR&hl=it&gl=IT&ceid=IT:it",
        "publisher": "Google News",
        "reliability": "aggregator",
        "enabled": False,
    },
    {
        "id": "formez-performa-pa",
        "name": "Formez - PerForma PA",
        "kind": "html",
        "url": "https://www.formez.it/performa-pa",
        "publisher": "Formez PA",
        "reliability": "official",
        "enabled": True,
        "list_selector": "article, .views-row, .node, .item-list li",
        "title_selector": "h2, h3, .field-content a, .node-title",
        "link_selector": "a",
        "summary_selector": "p, .field-content, .content",
        "date_selector": ".date-display-single, time, .submitted, .meta",
    },
    {
        "id": "funzione-pubblica-notizie",
        "name": "Dipartimento Funzione Pubblica - Notizie",
        "kind": "html",
        "url": "https://www.funzionepubblica.gov.it/it/ministro/comunicazione/notizie/",
        "publisher": "Dipartimento della Funzione Pubblica",
        "reliability": "official",
        "enabled": True,
        "list_selector": "article, .views-row, .item-list li, .card",
        "title_selector": "h2, h3, .field-content a, .card-title",
        "link_selector": "a",
        "summary_selector": "p, .field-content, .card-text",
        "date_selector": "time, .date, .submitted",
    },
    {
        "id": "italia-domani-notizie",
        "name": "Italia Domani - Notizie",
        "kind": "html",
        "url": "https://www.italiadomani.gov.it/content/sogei-ng/it/it/home/notizie.html",
        "publisher": "Italia Domani",
        "reliability": "official",
        "enabled": True,
        "list_selector": "article, .cmp-teaser, .card, .news-item",
        "title_selector": "h2, h3, .cmp-teaser__title, .card-title",
        "link_selector": "a",
        "summary_selector": "p, .cmp-teaser__description, .card-text",
        "date_selector": "time, .cmp-teaser__date, .date",
    },
    {
        "id": "innovazione-notizie",
        "name": "Dipartimento Innovazione - Notizie",
        "kind": "html",
        "url": "https://innovazione.gov.it/notizie/",
        "publisher": "Dipartimento per la trasformazione digitale",
        "reliability": "official",
        "enabled": True,
        "list_selector": "article, .card, .news-card, .post",
        "title_selector": "h2, h3, .card-title, .entry-title",
        "link_selector": "a",
        "summary_selector": "p, .card-text, .entry-content",
        "date_selector": "time, .date, .entry-date",
    },
    {
        "id": "pa-digitale-2026",
        "name": "PA Digitale 2026",
        "kind": "html",
        "url": "https://padigitale2026.gov.it/avvisi-e-bandi/",
        "publisher": "Dipartimento per la trasformazione digitale",
        "reliability": "official",
        "enabled": True,
        "list_selector": "article, .card, .card-body, .news-item",
        "title_selector": "h2, h3, .card-title, .news-title",
        "link_selector": "a",
        "summary_selector": "p, .card-text",
        "date_selector": "time, .date, .posted-on",
    },
    {
        "id": "eu-fto-topic-list",
        "name": "EU Funding & Tenders - Topic List",
        "kind": "topic_catalog",
        "url": "https://ec.europa.eu/info/funding-tenders/opportunities/data/topic-list.html",
        "publisher": "European Commission",
        "reliability": "official",
        "enabled": True,
        "allowed_prefixes": [
            "DIGITAL",
            "HORIZON-CL4",
            "ERASMUS",
        ],
        "allowed_years": [2024, 2025, 2026],
    },
]
